using System.Collections;
using System.Collections.Generic;

using TMPro;
using Zenject;
using UnityEngine;
using UnityEngine.UI;

public class ARTopBar : MonoBehaviour
{
    [SerializeField] private Image _icon;
    [SerializeField] private Sprite _PriseIcon;
    [Space]
    [SerializeField] private TMP_Text _topText;
    [Space]
    [SerializeField] private Image _background;
    [Space]
    [SerializeField] private TMP_Text _counter;

    [Inject] private readonly ClientDataService _clientDataService;

    private void Start()
    {
        _topText.text = _clientDataService
            .citiesTranslation[_clientDataService.data.city];

        _counter.text = $"{_clientDataService.data.games.Count.ToString()}/10";
    }
}
